server:
  port: 8089

spring:
  application:
    name: qw-agent-line

logging:
  level:
    root: INFO
    com.qw.agent.line: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
